/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CounterUpper;

public class FuelCalculator {

    public int divideMass(int mass) {
        return mass/3;
    }

    public int subtractMass(int mass) {
        return mass-2;
    }

    public int calculateFuel(int mass) {
        int fuelNeeded = divideMass(mass);
        fuelNeeded = subtractMass(fuelNeeded);
        return fuelNeeded;
    }
}
