/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CounterUpper;

public class FuelCalculator {

    private int divideMass(int mass) {
        return mass/3;
    }

    private int subtractMass(int mass) {
        return mass-2;
    }

    public int calculateFuel(int mass) {
        int fuelNeeded = divideMass(mass);
        fuelNeeded = subtractMass(fuelNeeded);
        return fuelNeeded;
    }

    public int calculateAll(int[] masses) {
        int totalFuelNeeded = 0;
        for (int mass : masses) {
            totalFuelNeeded += calculateFuel(mass);
        }
        return totalFuelNeeded;
    }
}
